---
name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v1.2.4
        if: ${{ github.event.pull_request.assignee == null && join(github.event.pull_request.assignees) == '' }}
        with:
          configuration-path: .github/auto_assign.yml
